### ISSUE TITLE
Not possible to set higher priority on repos defined via "version_os_repo_mapping"

### ISSUE THREAD

**Issue by smithfarm** [SUSE/sesdev#162]
This problem came to my attention when I tried to achieve the correct set of repos for the ceph in `Devel:Storage:7.0:CR`. Since this contains an "unadulterated" upstream build, the RPM version number is merely `15.1.0`, which is lower than the `15.1.0.1521` that is on the `SUSE:SLE-15-SP2:Update:Products:SES7` "Media1" image, even though the upstream build is newer. As a result ceph-salt was installing cephadm 15.1.0.1521 - because that's what zypper was evaluating as the newest version available in the repos.

The fix would be to allow the user to set an explicit zypper priority on a per-repo basis.

For example, like this:

```
version_os_repo_mapping:
    ses7:
        sles-15-sp2:
            - 'http://download.suse.de/ibs/SUSE:/SLE-15-SP2:/Update:/Products:/SES7/images/repo/SUSE-Enterprise-Storage-7-POOL-x86_64-Media1/'
            - '96!http://download.suse.de/ibs/Devel:/Storage:/7.0:/CR/SLE_15_SP2/'
```

In my mind, it makes sense to include the priority inside the repo URL string using a "magic prefix" (like `96!`, meaning "set repo priority to 96") for two reasons:

1. this is the same convention that teuthology's install task uses
2. it doesn't make the config.yaml structure any more complicated than it already is
