### ISSUE TITLE
DeepSea Stage 0 fails transiently when network is slow

### ISSUE THREAD

**Issue by smithfarm** [SUSE/sesdev#359]
Things like this happen when running `sesdev create ses5` over an openVPN connection:

```
    master: ++ echo '***** RUNNING stage.0 *******'
    master: ++ deepsea stage run --simple-output ceph.stage.0
    master: Starting stage: ceph.stage.0
    master: Parsing stage ceph.stage.0 steps...
    master: fail
    master:
    master: An error occurred when rendering one of the following states:
    master:     - ceph.salt-api, ceph.updates, ceph.metapackage, ceph.sync, ceph.repo (/srv/salt/ceph/s
alt-api, ceph/updates, ceph/metapackage, ceph/sync, ceph/repo)
    master: Error description:
    master:   - master.ses5-1node.test:
Command '['vagrant', 'up']' failed: ret=1 stderr:
```

```
    master: [14/14] Executing state ceph.updates...
    master:          node1.ses5-4node.test... fail
    master:          master.ses5-4node.test... ok
    master:          node3.ses5-4node.test... ok
    master:          node2.ses5-4node.test... ok
    master: Finished stage ceph.stage.0: succeeded=13/14 failed=1/14
    master:
    master: Failures summary:
    master: ceph.updates (/srv/salt/ceph/updates):
    master:   node1.ses5-4node.test:
    master:     The function "state.sls" is running as PID 15396 and was started at 2020, Jun 20 12:13:09.335465 with jid 20200620121309335465
Command '['vagrant', 'up']' failed: ret=1 stderr:
```

It is transient. ATM I have no idea why it happens, but I don't see it when running sesdev on machines in the office. Only when running on a machine at home over openVPN.
