### ISSUE TITLE
Not possible to ssh into cluster when deployment fails due to zypper issues early in provision phase

### ISSUE THREAD

**Issue by smithfarm** [SUSE/sesdev#360]
After `sesdev create` failed early in the provisioning phase with:

```
    master: Repository 'Main Update Repository' is invalid.
    master: [repo-update|http://download.opensuse.org/update/leap/15.1/oss/] Valid metadata not found at specified URL
    master: History:
    master:  - [|] Error trying to read from 'http://download.opensuse.org/update/leap/15.1/oss/'
    master:  - Download (curl) error for 'http://download.opensuse.org/update/leap/15.1/oss/content':
    master: Error code: Connection failed
    master: Error message: Could not resolve host: download.opensuse.org
    master:
    master:
    master: Please check if the URIs defined for this repository are pointing to a valid repository.
    master: Skipping repository 'Main Update Repository' because of the above error.
    master: Could not refresh the repositories because of errors.
Command '['vagrant', 'up']' failed: ret=1 stderr:
```

I was unable to ssh in to debug:

```
$ sesdev ssh nautilus-mini
Warning: Permanently added '192.168.121.227' (ECDSA) to the list of known hosts.
Password:

Aborted!
```
