### ISSUE TITLE
qa: curl returned non-zero exit status in rgw test

### ISSUE THREAD

**Issue by smithfarm** [SUSE/sesdev#369]
Transient failure in RGW test:

```
    master: + curl --silent --show-error http://master:80
    master: + tee /tmp/rgw_test.xml
    master: c
    master: u
    master: r
    master: l
    master: :
    master:  
    master: (
    master: 7
    master: )
    master:  
    master: F
    master: a
    master: i
    master: l
    master: e
    master: d
    master:  
    master: t
    master: o
    master:  
    master: c
    master: o
    master: n
    master: n
    master: e
    master: c
    master: t
    master:  
    master: t
    master: o
    master:  
    master: m
    master: a
    master: s
    master: t
    master: er port 80: Connection refused
    master: + test -f /tmp/rgw_test.xml
    master: + xmllint /tmp/rgw_test.xml
    master: /tmp/rgw_test.xml:1: parser error : Document is empty
```

Presumably, the RGW was just not quite ready to serve requests.
