### ISSUE TITLE
ci: capture ceph and salt logs for failed tests

### ISSUE THREAD

**Issue by tserong** [SUSE/sesdev#691]
We've recently had intermittent failures during deployment when running sesdev-integration in jenkins. The relevant part of the sesdev output is:

```
    master: [2023-04-14 04:55:32.031051] [master.mini.test] [STAGE] [BEGIN] Prepare to bootstrap the Ceph cluster
    master: [2023-04-14 04:55:32.079906] [master.mini.test] [STEP ] [BEGIN] Download ceph container image
    master: 
    master: Finished execution of ceph-salt formula
    master: 
    master: Summary: Total=1 Succeeded=0 Warnings=0 Failed=1
    master: "ceph-salt apply" exit code: 0
    [...]
    master: +++ ssh master.mini.test cephadm ls
    master: MONs in cluster (actual/expected): 1/1 (3080 seconds to timeout)
    master: MGRs in cluster (actual/expected): 1/1 (3080 seconds to timeout)
    master: +++ set +x
    master: ++ ceph status
    master: 2023-03-24T10:19:36.718+0000 7f3ef1ca5700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
    master: 2023-03-24T10:19:36.718+0000 7f3ef1ca5700 -1 AuthRegistry(0x7f3eec05ed08) no keyring found at /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,, disabling cephx
    master: 2023-03-24T10:19:36.818+0000 7f3ef1ca5700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
    master: 2023-03-24T10:19:36.818+0000 7f3ef1ca5700 -1 AuthRegistry(0x7f3ef1ca3f50) no keyring found at /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,, disabling cephx
    master: 2023-03-24T10:19:36.858+0000 7f3eeb7fe700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [1]
    master: 2023-03-24T10:19:36.862+0000 7f3ef1ca5700 -1 monclient: authenticate NOTE: no keyring found; disabled cephx authentication
    master: [errno 13] RADOS permission denied (error connecting to the cluster)
```

As best as I can tell, it does at least part of the bootstrap, but then something fails and it doesn't get any further. I think it's extremely weird that we get `Summary: Total=1 Succeeded=0 Warnings=0 Failed=1` but with no other error output saying what failed. Also, I'm surprised `ceph-salt apply` has an exit code of zero in this case.

I tried to add some extra logging to sesdev itself if deployment fails at this point (see #689), but haven't been able to reproduce the problem since my latest addition of ceph-salt.log so I still don't know what the problem is (or was), and anyway, it really shouldn't be up to sesdev to capture log files.

Can we make jenkins capture `/var/log/ceph/*`, `/var/log/salt/*` and `/var/log/ceph-salt.log` when tests fail? That way next time we hit this error I'll hopefully be able to figure out what's going wrong.
